#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#lemonbar -g x28 -B "#373737" -F "#DFDFDF" -f "JetBrainsMono Nerd Font Mono"

bspc monitor -d 1 2 3 4 5 6 7 8 9 =[]

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8'
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#111111"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color '#557700'

setxkbmap -layout us,ru -option grp:shifts_toggle
xset r rate 220 40
xmodmap -e "keycode 135 = Super_R"
xset -dpms
xset s off

feh --bg-center $HOME/wallpapers/blackpink.jpg

conky | lemonbar -g x28 -B "#373737" -F "#DFDFDF" -f "JetBrainsMono Nerd Font Mono"


